<a href="https://colab.research.google.com/github/shreyus3003/MLOps/blob/main/MLops_udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/futurexskill/ml-model-deployment/


Cloning into 'ml-model-deployment'...
remote: Enumerating objects: 215, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 215 (delta 2), reused 0 (delta 0), pack-reused 205
Receiving objects: 100% (215/215), 3.02 MiB | 17.21 MiB/s, done.
Resolving deltas: 100% (97/97), done.


In [3]:
import numpy as np
import pandas as pd

In [13]:
training_data = pd.read_csv('/content/ml-model-deployment/storepurchasedata.csv')
training_data.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   50000          1

In [ ]:
x = training_data.iloc[:, :-1].values
x
y = training_data.iloc[:, -1].values
y

In [63]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=20, random_state=0)
x_train

array([[   31, 50000],
       [   23, 35000],
       [   35, 56000],
       [   32, 45000],
       [   54, 78000],
       [   25, 32000],
       [   52, 65000],
       [   19, 22000],
       [   44, 51000],
       [   30, 45000],
       [   50, 45000],
       [   42, 45000],
       [   24, 30000],
       [   41, 63000],
       [   39, 30000],
       [   37, 23000],
       [   27, 37000],
       [   59, 90000],
       [   21, 28000],
       [   18, 20000]])

In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)
X_train

array([[-0.34724994,  0.29993804],
       [-1.01664741, -0.51807479],
       [-0.0125512 ,  0.62714317],
       [-0.26357526,  0.02726709],
       [ 1.5772678 ,  1.82689531],
       [-0.84929805, -0.68167735],
       [ 1.40991843,  1.11795086],
       [-1.35134615, -1.22701924],
       [ 0.74052096,  0.35447222],
       [-0.43092462,  0.02726709],
       [ 1.24256906,  0.02726709],
       [ 0.57317159,  0.02726709],
       [-0.93297273, -0.79074573],
       [ 0.4894969 ,  1.00888248],
       [ 0.32214753, -0.79074573],
       [ 0.15479817, -1.17248505],
       [-0.68194868, -0.40900641],
       [ 1.99564122,  2.48130557],
       [-1.18399678, -0.89981411],
       [-1.43502084, -1.33608761]])

In [76]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)

In [77]:
# np.ravel(y_train)
# np.ravel(y_test)

classifier.fit(X_train, y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [78]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [79]:
y_prob = classifier.predict_proba(X_test)[:,1]
y_prob

array([0.2, 0.2, 0. , 0.2, 0.4, 0.2, 0.2, 0.2, 0.2, 0.6, 0.4, 0.4, 1. ,
       0.2, 1. , 0.4, 1. , 0.2, 0.8, 0.2])

In [80]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[6, 0],
       [9, 5]])

In [81]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.55


In [ ]:
new_pred = classifier.predict(sc.transform(np.array([[42, 500000]])))
new_pred

In [86]:
import pickle
model_file = "classifier.pickle"
pickle.dump(classifier, open(model_file, 'wb'))
scaler_file = "sc.pickle"
pickle.dump(sc, open(scaler_file, 'wb'))

In [88]:
!pwd

/content


In [4]:
import pickle
import numpy as np
local_clasifier = pickle.load(open('/content/classifier.pickle', 'rb'))
local_scaler = pickle.load(open('/content/sc.pickle', 'rb'))

In [9]:
new_pred = local_clasifier.predict(local_scaler.transform(np.array([[48, 200000]])))
new_pred

array([1])